[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.rasterio",
  "python311Packages.geopandas",
  "python311Packages.shapely",
  "python311Packages.pyproj",
  "python311Packages.numpy",
  "python311Packages.pandas",
  "gdal",
  "geos",
  "proj"
]

[phases.install]
cmds = [
  "pip install --break-system-packages flask flask-cors requests polyline"
]

[phases.build]
cmds = []

[start]
cmd = "python3 backend.py"

