[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "expat",
  "gdal",
  "geos",
  "proj",
  "sqlite",
  "zlib",
  "libjpeg",
  "libpng"
]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 backend.py"

